name: Run My Code

on:
  push:
    branches: [main]

jobs:
  run_code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Script
        run: |
          echo "Hello, world!"
          # Replace this with your actual command. For example:
          # python First\ Program/your_script.py  